
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    short: "0.0.55",
    version: "0.0.55 (84c508b98c165b954118a6b17a7eee32)",
    buildSeed: 1616123409405,
};
