
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    short: "0.0.54",
    version: "0.0.54 (39b4f477e2d49ea27001142ba5ff1148)",
    buildSeed: 1615870417130,
};
