
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    short: "0.0.55",
    version: "0.0.55 (69718b2664353cbfa3b26f37fe4af5ea)",
    buildSeed: 1616123084230,
};
